services:
  - type: web
    name: khuje-nao-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --bind 0.0.0.0:$PORT wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.13
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: APPWRITE_ENDPOINT
        sync: false
      - key: APPWRITE_PROJECT_ID
        sync: false
      - key: APPWRITE_API_KEY
        sync: false
      - key: APPWRITE_STORAGE_BUCKET_ID
        sync: false
